oluka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('students.urls')),
    path('', include('frontend.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Oluaka Portal"
admin.site.site_title = "Oluaka Portal Administration"
admin.site.index_title = "Welcome To Oluaka Portal Administration"

students/urls.py
from django.urls import path
from students import views as student_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', student_views.dashboard_view,name='dashboard'),
    path('enroll/', student_views.enroll_view,name='enroll'),
    path('crash-course/', student_views.crash_course_view,name='crash_course'),
    path('full-course/', student_views.full_course_view,name='full_course'),
    path('student-profile/', student_views.student_profile_view,name='student_profile'),    
    path('upload-waec/', student_views.upload_waec_view,name='upload_waec'),    
    path('upload-jamb/', student_views.upload_jamb_view,name='upload_jamb'),    
    path('upload-guardian/', student_views.upload_guardian_view,name='upload_guardian'),    
    # path('login/', student_views.login_view,name='login'),    
    path('grade/', student_views.grade_view,name='grade'),    
    path('profile/', student_views.profile_view,name='profile'),     
    # path('register/', student_views.register_view,name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image

User = get_user_model()


class Student(models.Model):
    class CourseType(models.TextChoices):
        Computer_Hardware_Engineering = "Computer Hardware Engineering"
        Computer_Software_Engineering ="Computer Software Engineering"
        Networking_and_System_Security = "Networking And System Security"

    class StateType(models.TextChoices):
        Abia ="Abia"
        Adamawa ="Adamawa"
        Akwa_Ibom ="Akwa Ibom"
        Anambra ="Anambra"
        Bauchi ="Bauchi"
        Bayelsa ="Bayelsa"
        Benue ="Benue"
        Borno ="Borno"
        Cross_River ="Cross River"
        Delta ="Delta"
        Ebonyi ="Ebonyi"
        Edo ="Edo"
        Ekiti ="Ekiti"
        Enugu= "Enugu"
        Gombe= "Gombe"
        Imo="Imo"
        Jigawa= "Jigawa"
        Kaduna= "Kaduna"
        Kano= "Kano"
        Katsina= "Katsina"
        Kebbi= "Kebbi"
        Kogi= "Kogi"
        Kwara ="Kwara"
        Lagos ="Lagos"
        Nasarawa = "Nasarawa"
        Niger = "Niger"
        Ogun = "Ogun"
        Ondo = "Ondo"
        Osun = "Osun"
        Oyo = "Oyo"
        Plateau = "Plateau"
        Rivers = "Rivers"
        Sokoto = "Sokoto"
        Taraba = "Taraba"
        Yobe = "Yobe"
        Zamfara = "Zamfara"
        Federal_Capital_Territory= "Federal Capital Territory"
    
    class CoursePlan(models.TextChoices):
        crash_course = "Crash Course"
        part_time ="Part Time"
        full_time = "Regular"

    class HighestLevelOfEducation(models.TextChoices):
        High_School_Diploma = "High School Diploma"
        Degree = "Degree"
        Masters = "Masters"
        ND= "ND"
        HND = "HND"
    
    class Gender(models.TextChoices):
       Male = "Male"
       Female = "Female"
    
    class Employment(models.TextChoices):
        employed = "Employed"
        umemployed = "UnEmployed"
        self_employed= "Self-Employed"
        student = "Student"
    
    class Relationship(models.TextChoices):
        Brother = "Brother"
        Sister = "Sister"
        Father = "Father"
        Mother = "Mother"
        Relative = "Relative"
    
    student_fname = models.CharField(max_length=100)
    reg_no = models.CharField(max_length=100 , blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    student_email = models.EmailField(max_length=100)
    image = models.ImageField(verbose_name='image',null=True, blank=True)
    student_address = models.CharField(max_length=100)
    student_phone = models.CharField(max_length=15)
    highest_level_of_education = models.CharField(max_length=100, choices=HighestLevelOfEducation.choices)
    dob = models.DateField(null=True)
    employment_status = models.CharField(max_length=100, choices=Employment.choices, null=True, blank=True)
    employer_name = models.CharField(max_length=100, null=True, blank=True)
    desired_course = models.CharField(max_length=100, null=True, blank=True )
    referal_code = models.CharField(max_length=100, null=True, blank=True )
    disability = models.BooleanField(default=False)
    gender = models.CharField(max_length=100, choices=Gender.choices, blank=True,null=True)
    state_of_origin = models.CharField(max_length=100, choices=StateType.choices)
    state_of_residence = models.CharField(max_length=100, choices=StateType.choices)
    city = models.CharField(max_length=100)
    course_of_choice = models.CharField(max_length=100, choices=CourseType.choices,blank=True, null=True)
    course_of_choice2 = models.CharField(max_length=100, choices=CourseType.choices,blank=True, null=True) 
    course_enrolled = models.BooleanField(default=False)
    course_plan = models.CharField(max_length=100, choices=CoursePlan.choices)
    nextOfKinFullName = models.CharField(max_length=100, blank=True)
    nextOfKinEmail = models.EmailField(max_length=100, blank=True)
    nextOfKinPhone = models.CharField(max_length=100, blank=True)
    nextOfKinAddress = models.CharField(max_length=100, blank=True)
    nextOfKinRelationship = models.CharField(max_length=100, choices=Relationship.choices, blank=True)


    def __str__(self):
        return self.student_email
    
    class Meta:
        verbose_name_plural = "student"

class Guardian(models.Model):
    class ParentStateType(models.TextChoices):
        Abia ="Abia"
        Adamawa ="Adamawa"
        Akwa_Ibom ="Akwa Ibom"
        Anambra ="Anambra"
        Bauchi ="Bauchi"
        Bayelsa ="Bayelsa"
        Benue ="Benue"
        Borno ="Borno"
        Cross_River ="Cross River"
        Delta ="Delta"
        Ebonyi ="Ebonyi"
        Edo ="Edo"
        Ekiti ="Ekiti"
        Enugu= "Enugu"
        Gombe= "Gombe"
        Imo="Imo"
        Jigawa= "Jigawa"
        Kaduna= "Kaduna"
        Kano= "Kano"
        Katsina= "Katsina"
        Kebbi= "Kebbi"
        Kogi= "Kogi"
        Kwara ="Kwara"
        Lagos ="Lagos"
        Nasarawa = "Nasarawa"
        Niger = "Niger"
        Ogun = "Ogun"
        Ondo = "Ondo"
        Osun = "Osun"
        Oyo = "Oyo"
        Plateau = "Plateau"
        Rivers = "Rivers"
        Sokoto = "Sokoto"
        Taraba = "Taraba"
        Yobe = "Yobe"
        Zamfara = "Zamfara"
        Federal_Capital_Territory= "Federal Capital Territory"

    class Relationship(models.TextChoices):
        Brother = "Brother"
        Sister = "Sister"
        Father = "Father"
        Mother = "Mother"
        Relative = "Relative"   
    guardian = models.ForeignKey(Student, on_delete=models.CASCADE, blank=True, null=True)
    parent_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    occupation = models.CharField(max_length=100)
    phone_no  = models.CharField(max_length=15)
    email = models.EmailField(max_length=100)
    city = models.CharField(max_length=30)
    State = models.CharField(max_length=100, choices=ParentStateType.choices)
    relationship  = models.CharField(max_length=100, choices=Relationship.choices)

    def __str__(self):
        return self.email


class Admission(models.Model):
    student   = models.OneToOneField(Student, on_delete=models.CASCADE)
    admitted = models.BooleanField(default=False)

class JambUpload(models.Model):
    class Subject(models.TextChoices):
        English = "English"
        Mathematics = "Mathematics"
        Biology = "Biology"
        Physics = "Physics"
        Chemistry =  "Chemistry"  
    jamb_score = models.OneToOneField(Student, on_delete=models.CASCADE, blank=True, null=True)
    reg_no = models.CharField(max_length=30)
    exam_No = models.CharField(max_length=30)
    centre_name = models.CharField(max_length=80)
    subject1 = models.CharField(max_length=20, choices=Subject.choices)
    subject2 = models.CharField(max_length=20, choices=Subject.choices)
    subject3 = models.CharField(max_length=20, choices=Subject.choices)
    subject4 = models.CharField(max_length=20, choices=Subject.choices)
    score1 = models.FloatField()
    score2= models.FloatField()
    score3 = models.FloatField()
    score4 = models.FloatField()

    def total(self):
        return self.score1 + self.score2 + self.score3 + self.score4

class WAEC(models.Model):
    waec = models.OneToOneField(Student,on_delete=models.CASCADE)
    result = models.ImageField(verbose_name='waec') 
    accept = models.BooleanField(default=False)

    def __str__(self):
        return "WAEC"

class StudentMessages(models.Model):
    to = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.CharField(max_length=200)
    date = models.DateField()

    def __str__(self):
        return self.message
    
    class Meta:
        verbose_name_plural = "Messages"
        

students/forms.py
from django import forms
from .models import *


class WAECForm(forms.ModelForm):

    class Meta:
        model = WAEC
        fields = ['result','accept']

students/templates/students/student/upload-guardian.html
{% extends "students/base.html" %}

{% block content %}

{% if admission.admitted %}
<!-- Form Row -->

<div class="row">
    <div class="col-xl-12 col-md-12 mb-12">
        <div class="card">
            <div class="card-header">
                Oluaka Institute
            </div>
            <div class="text-center">
                <div class="card-body">
                    <h5 class="card-title">Update Guardian Details</h5>
                    <!-- <form class="text-capitalize"> -->
                    <!-- <div class="form-row">
                                                <div class="form-group col-md-6">
                                                    <label for="name">name</label>
                                                    <input type="name" class="form-control" id="name">
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="email">Email</label>
                                                    <input type="email" class="form-control" id="email">
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="phone">phone</label>
                                                    <input type="number" class="form-control" id="phone" placeholder="phone number">
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label for="relationship">relationship</label>
                                                    <select class="form-control" id="relationship">
                                                        <option>Choose..</option>
                                                        <option>Son</option>
                                                        <option>Daughter</option>
                                                        <option>Niece</option>
                                                        <option>Nephew</option>
                                                        <option>Cousin</option>
                                                    </select>
                                                </div>
                                                <div class="form-group col-md-8">
                                                    <label for="address">Address</label>
                                                    <input type="text" class="form-control" id="address"
                                                        placeholder="Apartment, studio, or floor">
                                                </div>
                                                <div class="form-group col-md-4">
                                                    <label for="occupation">occupation</label>
                                                    <select class="form-control" id="occupation">
                                                        <option>Choose..</option>
                                                        <option>Civil Servant</option>
                                                        <option>Self Employed</option>
                                                        <option>UnEmployed</option>
                                                    </select>
                                                </div> -->
                    <div class="row card-body">
                        <div class="row">
                            <div class="col-xl-4 col-md-4 mb-4">
                                <table class="table table-bordered">
                                    <thead>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row">Name</th>
                                            <td>Kshiti Ghelani</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Email</th>
                                            <td>kshitighelani@gmail.com</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Phone</th>
                                            <td colspan="2">123 456 7890</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Relationship</th>
                                            <td>Your Father</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Address</th>
                                            <td>in my house</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Occupation</th>
                                            <td>Nigerian Presido</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-xl-8 col-md-8 mb-8">
                            <!-- <h5 class="card-title">Update Guardian Details</h5> -->
                            <form>
                                <div class="form-row text-left">
                                    <div class="form-group col-md-6">
                                        <label for="inputName">Name</label>
                                        <input type="text" class="form-control" id="inputName">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="inputEmail4">Email</label>
                                        <input type="email" class="form-control" id="inputEmail4">
                                    </div>
                                </div>
                                <div class="form-row text-left">
                                    <div class="form-group col-md-6">
                                        <label for="inputCity">City</label>
                                        <input type="text" class="form-control" id="inputCity">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="inputState">State</label>
                                        <select id="inputState" class="form-control">
                                            <option selected>Choose...</option>
                                            <option>Abia</option>
                                            <option>Adamawa</option>
                                            <option>Akwa Ibom</option>
                                            <option>Anambra</option>
                                            <option>Bauchi</option>
                                            <option>Bayelsa</option>
                                            <option>Benue</option>
                                            <option>Borno</option>
                                            <option>Cross River</option>
                                            <option>Delta</option>
                                            <option>Ebonyi</option>
                                            <option>Edo</option>
                                            <option>Ekiti</option>
                                            <option>Enugu</option>
                                            <option>Gombe</option>
                                            <option>Imo</option>
                                            <option>Jigawa</option>
                                            <option>Kaduna</option>
                                            <option>Kano</option>
                                            <option>Katsina</option>
                                            <option>Kebbi</option>
                                            <option>Kogi</option>
                                            <option>Kwara</option>
                                            <option>Lagos</option>
                                            <option>Nasarawa</option>
                                            <option>Niger</option>
                                            <option>Ogun</option>
                                            <option>Ondo</option>
                                            <option>Osun</option>
                                            <option>Oyo</option>
                                            <option>Plateau</option>
                                            <option>Rivers</option>
                                            <option>Sokoto</option>
                                            <option>Taraba</option>
                                            <option>Yobe</option>
                                            <option>Zamfara</option>
                                            <option>Federal Capital Territory</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label for="inputZip">Zip</label>
                                        <input type="text" class="form-control" id="inputZip">
                                    </div>
                                </div>
                                <div class="form-row text-left">
                                    <div class="form-group col-md-6">
                                        <label for="inputPhone">Phone</label>
                                        <input type="text" class="form-control" id="inputPhone">
                                    </div>
                                    <div class="form-group col-md-4">
                                        <label for="inputRelationship">Relationship</label>
                                        <select id="inputRelationship" class="form-control">
                                            <option selected>Choose...</option>
                                            <option>Brother</option>
                                            <option>Sister</option>
                                            <option>Father</option>
                                            <option>Mother</option>
                                            <option>Relative</option>
                                        </select>
                                    </div>
                                    <div class="form-group col-md-2">
                                        <label for="inputOccupation">Occupation</label>
                                        <input type="text" class="form-control" id="inputOccupation">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" id="inputAddress" placeholder="Address">
                                </div>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Form Row Ends Here -->

</div>
{% else %}
<h3>
    <span class="alert alert-info alert-dismissable">Not Yet Admitted !</span>
</h3>
{% endif %}


{% endblock content %}

students/templates/students/student/upload-jamb.html
{% extends "students/base.html" %}

{% block content %}

{% if admission.admitted %}
<!-- Form Row -->

<div class="row">
    <div class="col-xl-12 col-md-12 mb-12">
        <div class="card">
            <div class="card-header">
                Oluaka Institute
            </div>
            <div class="text-center">
                <div class="card-body">
                    <h5 class="card-title">Upload JAMB Result</h5>
                    <div class="row">
                        <table class="col-md-8 table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Subject</th>
                                </tr>
                            </thead>
                        </table>
                        <table class="col-md-4 table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">Score</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <form class="text-capitalize">
                        <div class="form-row">
                            <div class="form-group col-md-8">
                                <input type="text" class="form-control" placeholder="subjec-1">
                            </div>
                            <div class="form-group col-md-4">
                                <input type="number" required id='jambresult1' class="form-control">
                            </div>
                            <div class="form-group col-md-8">
                                <input type="text" class="form-control" placeholder="subjec-2">
                            </div>
                            <div class="form-group col-md-4">
                                <input type="number" required id='jambresult1' class="form-control">
                            </div>
                            <div class="form-group col-md-8">
                                <input type="text" class="form-control" placeholder="subjec-3">
                            </div>
                            <div class="form-group col-md-4">
                                <input type="number" required id='jambresult1' class="form-control">
                            </div>
                            <div class="form-group col-md-8">
                                <input type="text" class="form-control" placeholder="subjec-4">
                            </div>
                            <div class="form-group col-md-4">
                                <input type="number" required id='jambresult1' class="form-control">
                            </div>
                        </div>
                        <div class="text-capitalize text-center mt-4">
                            <h3>total score: 235</h3>
                        </div>

                        <button type="submit" class="btn btn-primary mt-4">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Form Row Ends Here -->
{% else %}
<h3>
    <span class="alert alert-info alert-dismissable">Not Yet Admitted !</span>
</h3>
{% endif %}


{% endblock content %}

students/templates/students/student/upload-waec.html
{% extends "students/base.html" %}

{% block content %}
{% if admission.admitted %}
<!-- Form Row -->

<div class="row">
    <div class="col-xl-12 col-md-12 mb-12">
        <div class="card">
            <div class="card-header">
                Oluaka Institute
            </div>
            <div class="text-center">
                <h5 class="mt-3 card-title">Update WAEC Result</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8 ">
                            <div class="container">
                                <div class="float-left">
                                    {% with student.waec_set.all|first as image %}
                                    <img src="{{ image.url }}" />
                                    {% endwith %} 
                                </div>
                            </div>
                        </div>
                        {% if student.waec.accept %}
                        {% else %}
                        <form class="col-md-4" enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group">
                                    <label for="WAEC">Upload WAEC RESULT</label>
                                    <!-- <input type="file" class="form-control" name="WAEC" id="WAEC"> -->                                
                                    {{ form.as_p }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-outline-primary mt-4">Update</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Form Row Ends Here -->
{% else %}
<h3>
    <span class="alert alert-info alert-dismissable">Not Yet Admitted !</span>
</h3>
{% endif %}


{% endblock content %}